version: '3.8'

services:

  api:
    build: .
    container_name: api
    environment:
      - PORT=80
      - DATABASE_URL=postgresql://postgres:postgres@tf-db.cmxfpu2rrcpx.us-east-1.rds.amazonaws.com:5432/tf-db?schema=public
    ports:
      - "80:80"
